; PlatformIO Project Configuration File
; LiFi Transmitter - Arduino Uno
; Upload to the TRANSMITTER Arduino only

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_speed = 115200
